# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ceb161f09910f4ccdd4b8b67d5e4f2df93852252d68c5d3f3b51443beaa9c37cc270536bd671c1b7336c1a4598358786385bd0db2d3bbc39d30e743fcd6021b

test:
  secret_key_base: 5538f9da86f3836d3e70930e3b83ad028a0b91ab7d6800953ee6ef991132c8b385b18adde39a5c3c31b460eb31f053afe81a560ff629d52e79203a92265d857d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
